replicaCount: 3
image:
  repository: ghcr.io/twehage/testapp
  pullPolicy: Always

imagePullSecrets:
  - name: prediger-githubpat-package-read
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations:
    kubernetes.io/change-cause: ##CHANGE-CAUSE##

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: 
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /##LOCATIONS_JSON##
    nginx.ingress.kubernetes.io/x-forwarded-prefix: /$1
    nginx.ingress.kubernetes.io/enable-cors: "true"
  hosts:
    - host: testapp.esb.test-prediger.de
      paths:
        - path: /(.*)
          pathType: ImplementationSpecific
  tls:
    - secretName: testapp-esb-test-prediger-de-tls
      hosts:
        - testapp.esb.test-prediger.de

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
