---
# Create the service account scoped to our `settings-stage` namespace with a secret to use
apiVersion: v1
kind: ServiceAccount
metadata:
  name: setstg-deploy-user
  namespace: testapp
secrets:
  - name: setstg-actions-deploy

---
# Create a role for it in that namespace
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: setstg-deploy-user-full-access
  namespace: testapp
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["*"]
  - apiGroups: ["", "extensions", "apps"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["actions.github.com"]
    resources: ["*"]
    verbs: ["*"]

---
# Bind that service account to the role we created above
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: setstg-deploy-user-view
  namespace: testapp
subjects:
  - kind: ServiceAccount
    name: setstg-deploy-user
    namespace: testapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: setstg-deploy-user-full-access

---
# Create the credential for us to use for deployment
apiVersion: v1
kind: Secret
metadata:
  name: setstg-actions-deploy
  namespace: testapp
  annotations:
    kubernetes.io/service-account.name: setstg-deploy-user
type: kubernetes.io/service-account-token
